FROM ubuntu:14.04
MAINTAINER Seva Dolgopolov "zavalit@gmail.com"

ENV REFRESHED_AT 10.02.2015

RUN apt-get update -yqq && apt-get -yqq install php5 php5-cli

EXPOSE 8081

#ENTRYPOINT ["php", "server.php"]


